apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "10"
  labels:
    released-by: atheno
  name: atheno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atheno
  template:
    metadata:
      labels:
        released-by: atheno
        app: atheno
    spec:
      containers:
        - name: atheno-container
          image: {{ .Values.athenoImage }} # gopaddle/gopaddle:{{ .Values.imageTag }}
          ports:
            - containerPort: 65080
          env:
            - name: CLUSTER_TYPE
              value: "{{ .Values.CLUSTER_TYPE }}"
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: atheno
            - name: DB_PASSWORD
              value: atheno
            - name: DB_NAME
              value: atheno_db
            - name: openAIKey
              value: "{{ .Values.openAPIKey }}"
            - name: GITHUB_TOKEN
              value: "{{ .Values.githubPersonalAccessToken }}"
            - name: COMPLIANCE_PATH
              value: /opt/gopaddle/kubeagent/
            - name: MODEL
              value: "{{ .Values.openAPIModel }}"

