apiVersion: v1
kind: Service
metadata:
  labels:
    released-by: atheno
  name: atheno-service
spec:
  type: NodePort
  ports:
    - port: 65080
      targetPort: 65080
      nodePort: 30003
  selector:
    app: atheno

